### ISSUE TITLE
Check mapping logic for glue data type to arrow data type

### ISSUE THREAD

**Issue by matthewmturner** [datafusion-contrib/datafusion-catalogprovider-glue#4] opened 2022-06-04 04:06 UTC
I tried using this with some of my data and got errors when mapping to arrow data types.

Specifically for glue type date and then also some nested data i have where there are struct and arrays.

It looks like you have logic for most / all arrow data types - were you able to test on real data and real catalog?  Anything I can provide to help?

**Comment by timvw** [comment] 2022-06-06 22:37
I tested this on a real catalog with real data as well. 
Don't think any of the tables contained "complex" (arrays and/or nested structs)

Some glue schema + sample data to reproduce the date issue would be helpful.

Will try to add some additional methods that allow the user to decide/specify what the schema strategy should be (map from glue schema or infer or ..)

**Comment by timvw** [comment] 2022-06-08 07:08
It took a while to remember, but the biggest pain point is indeed in the parsing of nested structs and maps (as that requires more than the current naive regex matching).

**Comment by timvw** [comment] 2022-06-08 15:10
Changing the implementation to use [Pest-parser](https://github.com/pest-parser/pest) instead of naive regular expressions..  Seems to work better.. 
https://github.com/datafusion-contrib/datafusion-catalogprovider-glue/pull/5

**Comment by matthewmturner** [comment] 2022-06-09 03:36
thanks! will try it out and report back.

**Comment by matthewmturner** [comment] 2022-06-09 03:44
got this error when trying with the v0.1.2

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { variant: ParsingError { positives: [Int, Boolean, BigInt, Float, Double, Binary, Timestamp, String, Decimal, ArrayType, MapType, StructType], negatives: [] }, location: Pos(0), line_col: Pos((1, 1)), path: None, line: "date", continued_line: None }', /Users/matth/.cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-catalogprovider-glue-0.1.2/src/catalog_provider/glue.rs:234:83
```

**Comment by timvw** [comment] 2022-06-09 05:26
Seems that I changed the behavior (panic while trying to register a table instead of returning an Err). 
Will fix that.

Also see that you have a column of datatype "date" which is currently not supported. 
Will add support for that as well.

**Comment by timvw** [comment] 2022-06-09 14:33
Failure of one registration will not  block/affect registration of another one.
For each table that is (tried to be) registered, you get back a result: 
 * Ok (when it's registered), 
 * Err (when it's not).

**Comment by matthewmturner** [comment] 2022-06-09 14:47
thanks! making progress. was able to register a bunch of tables.  having some other issues now.

i tried querying one of the tables that was registered and got:

```
read 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DataFusionError(ExternalError(Execution("Failed to map column projection for field listing_activities. Incompatiable data types List(Field { name: \"item\", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }) and List(Field { name: \"element\" data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None })"))))
```

Also it looks like non parquet format may not be enabled as none of my json tables were registered because of unsupported format. i can create separate issue for that though.

**Comment by timvw** [comment] 2022-06-09 15:19
Here is a headstart ;)

https://github.com/datafusion-contrib/datafusion-catalogprovider-glue/tree/support-json

It fails on the only json table I have at hand for testing though.. (Probably need to do something with SerDeInfo "parameters": {"paths": "array" } metadata in Glue)

**Comment by matthewmturner** [comment] 2022-06-09 16:52
Thanks!

I will check it out and let you know if any questions / comments.

**Comment by timvw** [comment] 2022-06-10 05:40
Closing this now that v0.1.6 is released 

Currently it is possible to decide on the strategy to use to determine the table schema

1/ Derive from Glue 
+ fast
- not always correct (eg: impossible to infer nullability of a column or signedness of a number)

2/ Infer from data
- slow
+ will match whatever datafusion believes that data looks like

**Closed by timvw** 2022-06-10 05:40 UTC

**Comment by matthewmturner** [comment] 2022-06-10 13:25
when i just create the table myself using `CREATE EXTERNAL TABLE ...` my list array has name `item` so i would have thought that was the right one.

**Comment by timvw** [comment] 2022-06-10 13:39
Looking at the arrow-datafusion code I only find entries for "item" and none for "element" so I will rename that to "item" again...

**Comment by AlJohri** [comment] 2022-10-30 16:02
@timvw  in arrow-datafusion, I _believe_ this pull request added the functionality to round trip the list element name: https://github.com/apache/arrow-datafusion/pull/2893
